#Se define los recipientes de las notificaciones
notifications:
  email:
    recipients:
      - flame.el22@gmail.com
      - msanchez.jose.94@gmail.com
    on_success: never
    on_failure: always

#Definicion de lenguaje y version de VM
language: java
jdk: openjdk11
#Para que utilice Mysql
services:
  - mysql

#Se Define guardar en cache la carpeta de maven
cache:
  directories:
    - $HOME/.m2

before_install:
  - mysql -e 'CREATE DATABASE misaulasunq;'
#Antes del scrip se instalan las dependencias de maven
before_script:
  - mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8 -Dmaven.javadoc.skip=true -B -V

#Se Ejecutan los test
script:
  - "mvn test -B"