#Se define los recipientes de las notificaciones
notifications:
  email:
    recipients:
      - flame.el22@gmail.com
      - msanchez.jose.94@gmail.com
    on_success: never
    on_failure: always

#Definicion de lenguaje y version de VM
language: java
jdk: openjdk11

#Se Define guardar en cache la carpeta de maven
cache:
  directories:
    - $HOME/.m2

#Para que utilice el servicio de Mysql de travis
services:
  - mysql

# Se agrega mysql server(mysql 5.7)
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

#Antes de correr los test hay que configurar la zona horaria de la DB y de la VM para que no haya diferencia de horario y rompan test
before_install:
  - export TZ=America/Argentina/Buenos_Aires # Se Configura la Zona horaria de la Maquina Virtual
  - mysql -e 'CREATE DATABASE misaulasunq;' # Se Crea la Base para los test
 
before_script:
  - sudo mysql -e "use misaulasunq; create user 'jose'@'*' identified by 'jose';grant all privileges on misaulasunq.* to 'jose'@'%' identified by 'jose' with grant option;flush privileges;" #Se crea el usuario del application properties y se le da permisos
  - sudo mysql -e "SET GLOBAL time_zone = '-3:00';" # Se setea la timezone de la base en -03:00
  - sudo mysql_upgrade
  - sudo service mysql restart
  #Antes del script se instalan las dependencias de maven
  - mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8 -Dmaven.javadoc.skip=true -B -V

#Se Ejecutan los test
script:
  - "mvn test -B"